---
paths:
  /search:
    controller: Zef::Controller::Search
    sub:        search
    parameters: 
      - name: author
        in:   body
        description: auth to search for (like) 
        optional:    true
      - name: module
        in:   body
        description: module name (like)
      - name: version
        in:   body
        description: module version to search (exact match)
        optional:    true
  /register:
    controller: Zef::Controller::User
    sub:        register
    parameters:
      - name: username
        in:   body
        description: username to register with
      - name: password
        in:   body
      - name: email
        in:   body
